### ISSUE TITLE
Uninstalling and other issues

### ISSUE THREAD

**Issue by ziwzih** [xupefei/QuickLook#130]
Hey whatsup. I figured I'd report some of the issues I've had with your software. 

First off, I love Quicklook. From the UI to the compatibility, t's hands down the best quick-looking software out there. 

The main issue I had with it (while running 3.1) was it constantly failing. Spacebar cause nothing to happen. restarting the app didn't work and it would function properly until I completely restarted my machine. 

I went to your git and found a new version available, wherein I decided to uninstall and re-install the newest version (hoping this would solve the issue). Since there is no uninstall option in any of the menus, and the app is NOT listed in the bank of "uninstallable" software from windows' uninstaller, I had to resort to fishing for each file almost individually. This was streamlined using some searching software but I am STILL UNABLE to delete every file associated with this app due to some permissions issues in a few of the folders it created. I am super disappointed at how much of a hassle that was and I hope it gets resolved in the future because I will be the first one back in line to use this thing.

**Comment by xupefei** [comment]
I am not quite sure why it does not appears in the uninstall list (it
should be there, if you are using the MSI package), and why you have a
permission issue because the QuickLook does not even require any special
permission while installing.

Are you using a appx version on a windows 10 OS? If so you can uninstall it
by rightflicking the icon in your start menu and select "uninstall".

As the last resort, the QuickLook is installed in your
appdata\local\programs\quicklook folder. Just delete it.
