### ISSUE TITLE
请问是否支持directory opus

### ISSUE THREAD

**Issue by TheKiteRunning** [xupefei/QuickLook#158]
您好，如题，directory opus上的pdf预览经常出问题，不知道您的软件是否支持这个资源管理器，谢谢！

**Comment by xupefei** [comment]
支持。

On 3 Jan 2018 08:58, "TheKiteRunning" <notifications@github.com> wrote:

您好，如题，directory opus上的pdf预览经常出问题，不知道您的软件是否支持这个资源管理器，谢谢！

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xupefei/QuickLook/issues/158>, or mute the thread
