### ISSUE TITLE
Hide icon in notification area

### ISSUE THREAD

**Issue by sqqqs** [xupefei/QuickLook#191]
The icon has no function. Add options in the settings to hide it.

**Comment by xupefei** [comment]
Unfortunately no. The icon is the only way to quit QuickLook.
Moreover, even if there is an option in Settings, hiding icon means no way to get to it.

**Comment by sqqqs** [comment]
All settings can be done in the pop-up windows.
![2018-02-24_165318](https://user-images.githubusercontent.com/6069350/36631588-a9756fa4-1983-11e8-9231-3f39b42dbaaf.png)

**Comment by xupefei** [comment]
I don't think it is a good idea. First, all buttons here are related to the current file, but a Settings button, clearly, is not. Moreover, I wonder how many people will change settings so frequently that they see a head-up button during every previewing.

I will *not* add the "hide icon" function since Windows has already provided a way to hide useless try icons:
![image](https://user-images.githubusercontent.com/1687847/36636088-c7f09a82-19c7-11e8-828b-ce1156fd1963.png)

**Comment by xupefei** [comment]
Still a good news: you can make your own QuickLook because it is open-source!
I believe the icon can be removed by adding one line of code at https://github.com/xupefei/QuickLook/blob/master/QuickLook/TrayIconManager.cs#L62:
```
_icon.Visible = false;
```

**Comment by xupefei** [comment]
Solved in https://github.com/QL-Win/QuickLook/issues/729.
