### ISSUE TITLE
Closing a paused terminal with the spacebar triggers QuickLook

### ISSUE THREAD

**Issue by cbuchart** [xupefei/QuickLook#23]
1. User calls a batch file which internally calls `pause`  before finishing (`Press any key to continue . . .`).
2. User presses the <kbd>Spacebar</kbd> to close the window.
3. QuickLook unexpectedly previews the batch file.

Attached a very simple test case (it is zipped because cannot upload .bat directly)

[test.zip](https://github.com/xupefei/QuickLook/files/1040939/test.zip)

**Comment by xupefei** [comment]
Hi, I have tested this .bat file but the QuickLook didn't popped up. I think you are pressing the SPACE key when focusing the **file in explorer window**, not the cmd window.
QuickLook will popup preview window when (i) the current foreground window is the desktop or an explorer window & (ii) there is a file selected. Therefore the window should not pop up because (i) is not satisfied.

**Comment by cbuchart** [comment]
No, I've double-checked that the focus is on the terminal, otherwise the terminal windows wouldn't close. More information: Windows 10 (1703, 15063.296). If I can get more information about it I'll let you know.

**Comment by xupefei** [comment]
Thanks for the response. What version of quicklook are you using?

**Comment by cbuchart** [comment]
latest so far: 0.1.13

**Comment by xupefei** [comment]
Finally I figured out how to reproduce it issue. A `.bat` on Desktop would not work, but one in a explorer window.
I think it is because the KeyUp/KeyDown sequence. The cmd window closes in KeyDown, but QuickLook is handling KeyUp. I will fix this asap.

**Comment by cbuchart** [comment]
0.1.14 works flawlessly, nice bug fixing, thanks!
