### ISSUE TITLE
Does not display accent on files name in ZIP files

### ISSUE THREAD

**Issue by sergiopjf** [xupefei/QuickLook#24]
Does not display accent on files name in ZIP files

See attached screenshot.

![quicklook](https://cloud.githubusercontent.com/assets/18566003/26648536/28b8e316-4619-11e7-8278-5c39c98fcc5f.png)

**Comment by xupefei** [comment]
The .zip file is bad at handling multi-encoding since it has born. See https://marcosc.com/2008/12/zip-files-and-encoding-i-hate-you/.
There is nothing I can do.

**Comment by sergiopjf** [comment]
It works in others softwares.

![bandzip](https://cloud.githubusercontent.com/assets/18566003/26649015/b82b76fc-461a-11e7-9a67-b904545f5fd7.png)

**Comment by xupefei** [comment]
Bandizip has (and *needs*) the ability to detect encoding from strings because it is designed for uncompressing. However QuickLook is not as such: it is for quick previewing. So it is not critical for it to have such ability, especially when that ability may cost a lot of time to implement, but has only limited usage scenario.

**Comment by sergiopjf** [comment]
I respect your decision, but I do not agree.

Good luck with your project.

**Comment by xupefei** [comment]
Thank you for the understanding.

**Comment by xupefei** [comment]
I tried fix this issue today but unfortunately failed - the upstream SharpCompress library only provide forehead encoding setting, which is a paradox.

**Comment by xupefei** [comment]
I have submitted a RP for SharpCompress. Let's wait when it is merged.
