### ISSUE TITLE
Zoom Level Not Preserved

### ISSUE THREAD

**Issue by pmfaqtory** [xupefei/QuickLook#98]
Hi Paddy,

I'm using QuickLook on my Surface Pro 4. Every time that I view a PDF, the default size of the preview window is too small for me to see the text, so I zoom in to see the text.

The problem is that the next time that I press the space key on the file name, and the preview window displays, it reverts to the original size, which is much too small, so I have to zoom in again. 

The preview window should preserve the state (window dimensions and zoom level) from the previous invocation. 

Please fix this!

Thanks,

Steve

**Comment by xupefei** [comment]
The preview size can't be preserved across windows because it may cause problem when for example, 

> Let A be a PDF preview window. You zoomed in to see the text.
> Then you previewed another PDF file which has fonts big enough to be recognised without zooming in.

In such case preserving the windows size may downgrade the user experience.

However, I think it is okay for preserving windows size when **switching** previews, i.e., you click on (or select) another file **while a preview window is opening**, since most switching is going to a file which has similar characteristics.
